overrides:
  provider:
    puppetname: compute_provider
  password:
    # we set this as a parameter, because we can't get it back from the api
    behaviour: :parameter
  uuid:
    absent: true
  project_domain_id:
    absent: true
