composite_namevar:
  - usergroup
  - ldapname

overrides:
  name:
    puppetname: ldapname
  auth_source_id:
    readname: auth_source_ldap
    foreign_class: '::Puppet::Provider::ForemanAuthSourceLdap::ForemanAuthSourceLdap'
    requires: puppet/provider/foreman_auth_source_ldap/foreman_auth_source_ldap
