composite_namevar:
  - role
  - resource_type

extra:
  resource_type:
    puppetname: "resource_type"
    readname: "resource_type_label"
    writename: ~
    behaviour: :namevar
    type: "Data"
    desc: ""
    definition_class: AttrDefinition

overrides:
  role_id:
    readname: role
    detailed: false
  location_ids:
    absent: true
  organization_ids:
    absent: true
