extra:
  name:
    puppetname: name
    readname: name
    writename: ~
    type: String
    desc: name
    definition_class: AttrDefinition
    behaviour: :namevar
overrides:
  id:
    absent: true
  value:
    type: Data
