overrides:
  vlanid:
    type: Optional[Numeric]
  dhcp_id:
    foreign_class: '::Puppet::Provider::ForemanSmartProxy::ForemanSmartProxy'
    requires: puppet/provider/foreman_smart_proxy/foreman_smart_proxy
  tftp_id:
    foreign_class: '::Puppet::Provider::ForemanSmartProxy::ForemanSmartProxy'
    requires: puppet/provider/foreman_smart_proxy/foreman_smart_proxy
  httpboot_id:
    foreign_class: '::Puppet::Provider::ForemanSmartProxy::ForemanSmartProxy'
    requires: puppet/provider/foreman_smart_proxy/foreman_smart_proxy
  dns_id:
    foreign_class: '::Puppet::Provider::ForemanSmartProxy::ForemanSmartProxy'
    requires: puppet/provider/foreman_smart_proxy/foreman_smart_proxy
  template_id:
    foreign_class: '::Puppet::Provider::ForemanSmartProxy::ForemanSmartProxy'
    requires: puppet/provider/foreman_smart_proxy/foreman_smart_proxy
